dist: jammy
language: python
python:
  - "3.10"
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $awsaccesskeyid
  secret_access_key: $awssecretaccesskey
  region: "us-east-1"
  app: "swe1-app"
  env: "swe1-app-dev"
  bucket_name: "elasticbeanstalk-us-east-1-975050172613"
  on:
    branch: main

# test4
